### ISSUE TITLE
Pre-Caching part of the Hash

### ISSUE THREAD

**Issue by WhoSoup** [pegnet/LXR256#23]
I took a closer look at the Hashing algorithm today, particularly when combined with the data we input. For every iteration, the miner calculates the hash of `OPRHash | nonce`, meaning the first 32 bytes are always the same. The Hashing algorithm contains two steps, the first of which just runs across the entire range of input in order.

For every call to Hash from a miner, the first 32 iterations of step 1 will always be the same and yield the same data. So I decided to see what happens if you cache the values from step1 up until that point, continuing with just the nonce, and discovered it's a moderate speed improvement of 12%:

```
BenchmarkHash-8       	  300000	      6077 ns/op	     351 B/op	       3 allocs/op
BenchmarkPreCache-8   	  300000	      5370 ns/op	     352 B/op	       3 allocs/op
```

The pre-caching code is available here: https://github.com/WhoSoup/LXRHash/blob/a3b83647ad54f924cf0f18d457c2eeee29332ce0/lxrhash.go#L58-L105

The test file contains the two benchmarks as well as a test that checks whether the two different versions are the same: https://github.com/WhoSoup/LXRHash/blob/factomize-precache/lxrhash_test.go

An easy fix would be for miners to hash `nonce | OPRHash` instead. Precaching the millions of nonces is not faster than just calculating the hash for it, but putting the nonce first has a cascading effect oprhash. Alternatively, run step 1 from highest to lowest index.

**Comment by WhoSoup** [comment]
Saw there was an additional branch with a new implementation of Hash() in LXR-20. Pre-caching has an even greater benefit of 23%:
```
BenchmarkHash-8       	   20000	     96955 ns/op	     351 B/op	       2 allocs/op
BenchmarkPreCache-8   	   20000	     74854 ns/op	     352 B/op	       3 allocs/op
```

New pre-caching code: https://github.com/WhoSoup/LXRHash/blob/28a5c5586bcfa28085ac40521d2c13d72a0fe5d2/lxrhash.go#L127-L316
New pre-caching benchmark/test file: https://github.com/WhoSoup/LXRHash/blob/factomize-precache-new/lxrhash_test.go

**Comment by PaulSnow** [comment]
Good catch.

**Comment by PaulSnow** [comment]
I would propose that we do a fast spin through the source first and do another pass with our ByteMap.  So if we add:
```
       faststep := func(v2 uint64, idx uint64) {
		as = idx<<1 ^ idx>>3 ^ as<<7 ^ as>>5
		s1 = s1<<9 ^ s1>>3 ^ as
		as, s1, s2, s3 = s3, as, s1, s2
	}

        // Fast spin to prevent caching state
	for _, v2 := range src {
		if idx >= lx.HashSize { // Use an if to avoid modulo math
			idx = 0
		}
		faststep(uint64(v2), idx)
	}
```
Prior to the main loop, I cannot see a difference with or without the loop in terms of the benchmark code, but of course you can't pre-cache anything as the entire source is used to initialize the state.

**Comment by PaulSnow** [comment]
Shift XOR random number generators are some of the fastest.  https://en.wikipedia.org/wiki/Xorshift 
And our use case is generally hashing a 32 byte entry hash + nonce.  I don't think that double hashing would buy us anything, as our hash is really slow, and you could prefix the first pass.  But prefixing a very fast pass over the bytes would be useless.

**Comment by WhoSoup** [comment]
> I would propose that we do a fast spin through the source first and do another pass with our ByteMap. So if we add:

that works, it's not like we're trying to do things efficiently in this case :joy_cat:

**Comment by PaulSnow** [comment]
Maybe better, pass the nonce in as the seed for the hash.  Means we use up to a 8 byte  extids[0] as a uint64 value.

Came to me as I was driving home that I might be making this more complicated than I had to.

On the other hand, the fast first pass avoids a hashing attack that exists for any number of other applications, not just this case....

**Comment by PaulSnow** [comment]
Went with the pre-scan solution.  Merged.
