### ISSUE TITLE
Set the default size for the ByteMap 

### ISSUE THREAD

**Issue by PaulSnow** [pegnet/LXR256#25]
I would suggest we default to 30 bits (1 GB)
Remove references to a particular application (PegNet) from the code and comments.

**Comment by WhoSoup** [comment]
Just stumbled across this code. Generating a 1GB table takes a long time (took me 10 minutes and 4 seconds) and it's being generated by default, so just including the LXRHash package is going to make people generate the table even if it doesn't end up getting used. 

I strongly recommend removing these lines:
https://github.com/pegnet/LXRHash/blob/038e362dab0ddec62429a3e3cf7c671d1b62b2ef/constants.go#L13-L15

**Comment by PaulSnow** [comment]
It was 25 bits, which is > 6 bits faster (1/64 the data + fewer cache misses)

**Comment by PaulSnow** [comment]
If we use 1 gb for mining, then they will need to suffer that 10 minutes.  After which, it loads from disk.

**Comment by WhoSoup** [comment]
> If we use 1 gb for mining, then they will need to suffer that 10 minutes. After which, it loads from disk.

Sorry if my original post came across as criticizing your selection of 30 bits. It's not. It's about initializing the bytemap unnecessarily inside of the LXRHash package. 

Right now any project that imports LXRHash is going to have the 30 bits map initialized whether or not they actually want to use it:
https://github.com/pegnet/LXRHash/blob/038e362dab0ddec62429a3e3cf7c671d1b62b2ef/constants.go#L13-L15

but pegnet doesn't actually use this, it uses its own initialized table with 25 bits:
https://github.com/pegnet/pegnet/blob/1de90e5be3379355615b07a9b595f4234e2d7c77/opr/opr.go#L65-L72

The 30-bit change should be in the pegnet project! Right now it's initializing the 30-bits table and then never actually uses it.
