### ISSUE TITLE
Add File Headers

### ISSUE THREAD

**Issue by PaulSnow** [pegnet/LXR256#27]
Need file headers to conform to best practices using MIT License

**Comment by WhoSoup** [comment]
MIT license just requires a copy of the license to be distributed with any copies / substantial portions of code, which is satisfied by the LICENSE file. 

I personally think that adding copyright headers to every file is annoying and looked up some of the projects I recognized that are licensed under MIT. AngularJS, jQuery, PuTTY, Travis CI don't have any license headers. Godot has the full MIT license in every file header (lol). ZCash has MIT notifiers like factomd.

There doesn't seem to be a lot of cohesion. Where's the best practice for including license headers coming from?
