### ISSUE TITLE
Unit Tests were broken

### ISSUE THREAD

**Issue by PaulSnow** [pegnet/LXR256#31]
We did a reorg and removed the default instance of the LXRHash, and this broke the unit tests.

Other fixes include added the go mod support to create the vendor package, because we need to use a particular version of the factom go library.

Added vendor to the .gitignore

Put the set of configuration variables for the unit tests in the unit test directory.  It is hard on automated testing to use 1GB ByteMaps

**Comment by WhoSoup** [comment]
![image](https://user-images.githubusercontent.com/34172041/61853082-546c1e80-aebb-11e9-9174-488273e717a9.png)

the problem he's getting is because he's running the the test command wrong, not because the unit tests are broken. i'll let him know on discord and you can cross that off your todo list
