### ISSUE TITLE
Int overflow on Raspbian

### ISSUE THREAD

**Issue by JFletcherTaylor** [pegnet/LXR256#36]
Set up LXRHash on rpi.
Raspberry pi 3 model A +
4.14.98-v7+ Raspian OS
armv71 chip

Benchmark test fails with “overflows int”,

![image](https://user-images.githubusercontent.com/43154126/61965066-3cac9d00-af84-11e9-9825-e88e9a30fe60.png)
(Excuse the poor photo above ^ took a pic of it running on my tv :) )

This seems to be an issue generally with Go running on 32 bit systems. Here are some related issues:
https://stackoverflow.com/questions/26185795/int-overflow-on-32-bit-systems
https://github.com/thanos-io/thanos/issues/365
https://github.com/golang/go/issues/23086

I haven't worked with GO, so this issues beyond me.

**Comment by nklomp** [comment]
Please note that the new Raspberry PI 4 models are 64 bit :)

**Comment by Emyrk** [comment]
So these overflows are just in the unit tests, not the actual hash.
We just upped the unit tests to use int64s in the counters. This should now pass

**Comment by drkatz** [comment]
Thanks, this issue is now solved in the latest version
