### ISSUE TITLE
Investigate RAM Allocation

### ISSUE THREAD

**Issue by WhoSoup** [pegnet/LXR256#54]
While analyzing fatd ram allocation, I noticed that LXR sometimes eats up 2GB instead of the expected 1GB, with 1 GB being used for the bytemap (expected) and 1 GB being used in the ioutil.ReadFile buffer (not expected).  This allocated system memory then keeps sticking around sometimes, but other times it gets released.

We should investigate the behavior of this further and possibly instead of reading the entire file into memory via ReadFile, we can read it in chunks in order to avoid the additional allocation.

**Comment by Emyrk** [comment]
A user has reported this causing out of memory panics.
