### ISSUE TITLE
Race condition detected because of FirstIdx assignment

### ISSUE THREAD

**Issue by PaulBernier** [pegnet/LXR256#57]
When using LXRHash concurrently the Golang race condition detector will report something like this:

```bash
WARNING: DATA RACE
Write at 0x0000016da3c0 by goroutine 79:
  github.com/pegnet/LXRHash.(*LXRHash).Hash()
      /home/paul/go/pkg/mod/github.com/pegnet/!l!x!r!hash@v0.0.0-20190806215027-2c3ac3baf00d/lxrhash.go:101 +0x48b

Previous write at 0x0000016da3c0 by goroutine 78:
  github.com/pegnet/LXRHash.(*LXRHash).Hash()
      /home/paul/go/pkg/mod/github.com/pegnet/!l!x!r!hash@v0.0.0-20190806215027-2c3ac3baf00d/lxrhash.go:101 +0x48b
```
Which points to this assignment: https://github.com/pegnet/LXRHash/blob/master/lxrhash.go#L101
While I understand it doesn't have any impact on the LXR hash produced, it's annoying to have this warning shows up when testing my own software that uses LXR hash. Could this be somehow fixed so that this false-positive doesn't show up when testing race conditions? Thank you.

**Comment by PaulBernier** [comment]
It looks like `FirstIdx` is only used here: https://github.com/pegnet/LXRHash/blob/master/testing/nonce_test.go#L84 which is actually being used in a concurrent environment... so the race condition may very well happen in this test and skew the results.

**Comment by PaulSnow** [comment]
Just delete the test, and remove the variable is the right answer.  This test was being used to look at an attack vector where we could cache a bunch of work to speed up hashes.  We now do a fast process step to ensure you can't.  This test gave us some insight, but it isn't coded to fail or anything.
